import { api } from './api.js';
import { registerArmourObservation } from './armourObservation.js';
import { registerArtConfig } from './artConfig.js';
import { registerArtSummary } from './artSummary.js';
import { registerAutoReveal } from './autoReveal.js';
import { MODULE_ID } from './constants.js';
import { registerContextMenu } from './contextMenu.js';
import { registerHitPointObservation } from './hitPointObservation.js';
import { addHudButton } from './hudButton.js';
import { registerInspectRefresh, renderOpenInspects } from './inspect.js';
import { migrateRename } from './renameMigration.js';
import { registerSettings } from './settings.js';
import { registerTokenArt } from './tokenArt.js';
import { registerTokenRebuildSkip } from './tokenRebuild.js';
const log = Grimmtale.createLogger(MODULE_ID);
Hooks.once('init', () => {
    void foundry.applications.handlebars.loadTemplates([`modules/${MODULE_ID}/templates/item-row.hbs`]);
    registerSettings(renderOpenInspects);
    registerAutoReveal();
    registerArmourObservation();
    registerHitPointObservation();
    registerTokenRebuildSkip();
    registerInspectRefresh();
    registerContextMenu();
    registerTokenArt();
    registerArtConfig();
    registerArtSummary();
});
Hooks.once('ready', () => {
    void migrateRename();
    Grimmtale.publishApi(MODULE_ID, api, { gameAlias: 'interactableActors' });
    log.info('Ready');
});
Hooks.on('renderTokenHUD', addHudButton);
